test commit PR
historeno/enermaps pull request #24
Opened 2022-06-01 16:17 UTC by Arthurllyr

2022-06-03 10:51 UTC, cedricserugendo commented
`showInfos` seems to be a function that only returns a Boolean and not an object 
Did you check the returned result?
@Arthurllyr

2022-06-03 11:13 UTC, Arthurllyr commented
Indeed, showInfos seems to unlock the popup when there is some datas to show.

2022-06-09 14:39 UTC, cedricserugendo commented on frontend/src/src/components/CMList.svelte
> +//  import '../leaflet_components/L.TileLayer.QueryableLayer.css';
you should uncomment this lines

2022-06-13 07:49 UTC, cedricserugendo requested changes

2022-06-13 07:49 UTC, cedricserugendo commented on frontend/src/src/components/CMList.svelte
> +  // import {popupContent} from '../leaflet_components/L.TileLayer.QueryableLayer.js';
this line must be removed

2022-06-13 07:49 UTC, cedricserugendo commented on frontend/src/src/components/CMList.svelte
> +        </div>
by default you show all the information in the HTLM string, we want to show only few information, this part need modification

2022-06-13 07:49 UTC, cedricserugendo commented on frontend/src/src/components/Map.svelte
> +        // appel des datas contenues dans l'objet showInfos
this commented line is not useful I think

2022-06-13 07:49 UTC, cedricserugendo commented on frontend/src/src/leaflet_components/L.TileLayer.QueryableLayer.js
> +// export const popupContent  = writable(true);
not usefull

2022-06-13 07:49 UTC, cedricserugendo commented on frontend/src/src/leaflet_components/L.TileLayer.QueryableLayer.js
> +
not usefull

2022-06-13 07:49 UTC, cedricserugendo commented on frontend/src/src/leaflet_components/L.TileLayer.QueryableLayer.js
> +
not usefull

2022-06-13 07:49 UTC, cedricserugendo commented on frontend/src/src/leaflet_components/L.TileLayer.QueryableLayer.js
> +    popupContent += '<h3>' + title + '</h3>';
why have you change the tag ? according to me it's not necessarry

2022-07-05 17:35 UTC, cedricserugendo commented
@Arthurllyr, you can comment the PR like this as discussed

2022-07-05 17:41 UTC, Arthurllyr commented
> @Arthurllyr, you can comment the PR like this as discussed

do you understand the difference btw titles and rows ?

2022-07-05 17:52 UTC, cedricserugendo commented
> > @Arthurllyr, you can comment the PR like this as discussed
> 
> do you understand the difference btw titles and rows ?

The difference is clear, but can you send me a screenshot of the error you have with the latest version of the code?

2022-07-05 17:59 UTC, Arthurllyr commented
> > > @Arthurllyr, you can comment the PR like this as discussed
> > 
> > 
> > do you understand the difference btw titles and rows ?
> 
> The difference is clear, but can you send me a screenshot of the error you have with the latest version of the code?
![Capture d’écran 2022-07-05 195905](https://user-images.githubusercontent.com/19857553/177388047-bbb6cb1b-0a40-418b-b50d-af462eb6c277.png)

2022-07-07 12:22 UTC, cedricserugendo commented
> > > @Arthurllyr, you can comment the PR like this as discussed
> > 
> > 
> > do you understand the difference btw titles and rows ?
> 
> The difference is clear, but can you send me a screenshot of the error you have with the latest version of the code? ![Capture d’écran 2022-07-05 195905](https://user-images.githubusercontent.com/19857553/177388047-bbb6cb1b-0a40-418b-b50d-af462eb6c277.png)

we have already encountered this error 
You try to apply a 'length' method on an undefined object

2022-08-11 11:53 UTC, Arthurllyr commented
![popupcontent](https://user-images.githubusercontent.com/19857553/184127571-0abbd0bd-7601-4323-83a9-90081251909f.png)

2022-08-11 14:33 UTC, cedricserugendo approved these changes
from my side, this branch can be merged if Gilles and you, @Arthurllyr , are ok with that

2022-09-20 08:19 UTC, merged